# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: config-server
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: config-server
#   template:
#     metadata:
#       labels:
#         app: config-server
#     spec:
#       securityContext:
#         runAsNonRoot: true
#       nodeSelector:
#         role: micro
#       containers:
#       - name: config-server
#         securityContext:
#           allowPrivilegeEscalation: false
#         image: registry.gitlab.com/smarteventapp/config-server:main
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8888
#         env:
#         - name: SPRING_PROFILES_ACTIVE
#           value: "docker"
#         - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
#           value: "http://eureka-server:30000/eureka/"
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "50m"
#           limits:
#             memory: "512Mi"
#             cpu: "500m"
