apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        role: micro
      containers:
      - name: config-server
        securityContext:
          allowPrivilegeEscalation: false
        image: ghcr.io/esic-project-cloud/smartevent-ia-config-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
